server:
  port: 8200
spring:
  application:
    name: upload-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 49.232.78.84:22122

mingrui:
  upload:
    path:
      windows: D:\\images
      linux: /xzc/images
    img:
      #图片服务器主机
      host: http://49.232.78.84/